apiVersion: v1
kind: Service
metadata:
  name: {{ include "ambari-prom-exporter.fullname" . }}
  namespace: {{ default .Values.namespace .Release.Namespace  }}
  labels:
    {{- include "ambari-prom-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    {{- include "ambari-prom-exporter.selectorLabels" . | nindent 4 }}
