apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "ambari-prom-exporter.labels" . | nindent 6 }}
    {{ toYaml .Values.serviceMonitorLabels | nindent 6 }}
  name: {{ include "ambari-prom-exporter.fullname" . }}
  namespace: {{ default .Values.namespace .Release.Namespace  }}
spec:
  endpoints:
  - honorLabels: true
    port: metrics
    relabelings:
    - action: labeldrop
      regex: ^pod$
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
    {{- include "ambari-prom-exporter.labels" . | nindent 6 }}

