env:
  ambari:
    rm_url: "http://{{env}}-spark-cluster.azurehdinsight.net/ws/v1/cluster/metrics"
    metrics_url: "http://{{env}}-spark-cluster.azurehdinsight.net/api/v1/clusters/{{env}}-spark-cluster/host_components?fields=metrics/*"
    alert_url: "http://{{env}}-spark-cluster.azurehdinsight.net/api/v1/clusters/{{env}}-spark-cluster/alerts?format=summary
    user: admin
    pass: "{{ azure_spark_cluster_http_password }}"


#Hd cluster alert values
app_failed_critical: 1
nodes_inactive_critical: 1
